# Generated by Django 5.2.8 on 2025-11-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, verbose_name='Tên thành phố')),
                ('country_code', models.CharField(default='VN', max_length=5, verbose_name='Mã quốc gia')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
                ('timezone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Múi giờ')),
            ],
            options={
                'verbose_name': 'Vị trí',
                'verbose_name_plural': '1. Vị trí',
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='CurrentWeatherCache',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='current_weather_cache', serialize=False, to='Weather_App.location')),
                ('data', models.JSONField(verbose_name='Dữ liệu JSON từ API')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Cache thời tiết hiện tại',
                'verbose_name_plural': '2. Cache thời tiết hiện tại',
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_alert_id', models.CharField(max_length=100, unique=True)),
                ('event_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='Weather_App.location')),
            ],
            options={
                'verbose_name': 'Cảnh báo thời tiết',
                'verbose_name_plural': '5. Cảnh báo thời tiết',
            },
        ),
        migrations.CreateModel(
            name='AIForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(verbose_name='Ngày dự báo')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_temp_max', models.FloatField(verbose_name='Dự báo nhiệt độ max')),
                ('predicted_temp_min', models.FloatField(verbose_name='Dự báo nhiệt độ min')),
                ('predicted_precipitation_probability', models.FloatField(blank=True, null=True, verbose_name='Dự báo xác suất mưa (%)')),
                ('predicted_weather_code', models.IntegerField(blank=True, null=True, verbose_name='Dự báo mã thời tiết (WMO)')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_forecasts', to='Weather_App.location')),
            ],
            options={
                'verbose_name': 'Kết quả dự báo (AI)',
                'verbose_name_plural': '4. Kết quả dự báo (AI)',
                'ordering': ['forecast_date'],
                'unique_together': {('location', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(verbose_name='Ngày quan sát')),
                ('temp_avg', models.FloatField(blank=True, null=True, verbose_name='Nhiệt độ TB')),
                ('temp_max', models.FloatField(blank=True, null=True, verbose_name='Nhiệt độ max')),
                ('temp_min', models.FloatField(blank=True, null=True, verbose_name='Nhiệt độ min')),
                ('humidity_avg', models.FloatField(blank=True, null=True, verbose_name='Độ ẩm TB')),
                ('precipitation_total', models.FloatField(blank=True, null=True, verbose_name='Tổng lượng mưa')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='Weather_App.location')),
            ],
            options={
                'verbose_name': 'Dữ liệu lịch sử (AI Train)',
                'verbose_name_plural': '3. Dữ liệu lịch sử (AI Train)',
                'unique_together': {('location', 'observation_date')},
            },
        ),
    ]
