# Generated by Django 5.2.8 on 2026-01-07 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiforecast',
            options={'ordering': ['forecast_date'], 'verbose_name': 'Kết quả dự báo Daily (AI)', 'verbose_name_plural': '4. Kết quả dự báo Daily (AI)'},
        ),
        migrations.AlterModelOptions(
            name='weatheralert',
            options={'verbose_name': 'Cảnh báo thời tiết', 'verbose_name_plural': '6. Cảnh báo thời tiết'},
        ),
        migrations.AlterField(
            model_name='aiforecast',
            name='generated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Thời gian generate'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AIForecastHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_datetime', models.DateTimeField(verbose_name='Thời gian dự báo (giờ)')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian generate')),
                ('predicted_temp', models.FloatField(verbose_name='Dự báo nhiệt độ')),
                ('predicted_humidity', models.FloatField(blank=True, null=True, verbose_name='Dự báo độ ẩm (%)')),
                ('confidence_lower', models.FloatField(blank=True, null=True, verbose_name='CI Lower 95%')),
                ('confidence_upper', models.FloatField(blank=True, null=True, verbose_name='CI Upper 95%')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_forecasts_hourly', to='Weather_App.location')),
            ],
            options={
                'verbose_name': 'Kết quả dự báo Hourly (AI)',
                'verbose_name_plural': '5. Kết quả dự báo Hourly (AI)',
                'ordering': ['forecast_datetime'],
                'unique_together': {('location', 'forecast_datetime')},
            },
        ),
    ]
