# Generated by Django 5.2.6 on 2025-12-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
