# Generated by Django 5.2.8 on 2026-01-17 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatheralert',
            options={'verbose_name': 'Cảnh báo thời tiết', 'verbose_name_plural': '6. Cảnh báo thời tiết'},
        ),
        migrations.AlterField(
            model_name='location',
            name='city_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(verbose_name='Ngày dự báo')),
                ('temp_max', models.FloatField(verbose_name='Nhiệt độ cao nhất (°C)')),
                ('temp_min', models.FloatField(verbose_name='Nhiệt độ thấp nhất (°C)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_forecasts', to='Weather_App.location')),
            ],
            options={
                'verbose_name': 'Dự báo theo Ngày (5 ngày)',
                'verbose_name_plural': '5. Dự báo theo Ngày (5 ngày)',
                'ordering': ['forecast_date'],
                'unique_together': {('location', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField(verbose_name='Giờ dự báo')),
                ('temperature', models.FloatField(verbose_name='Nhiệt độ (°C)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Độ ẩm (%)')),
                ('shortwave_radiation', models.FloatField(blank=True, null=True, verbose_name='Bức xạ (W/m²)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_forecasts', to='Weather_App.location')),
            ],
            options={
                'verbose_name': 'Dự báo theo Giờ (24h)',
                'verbose_name_plural': '4. Dự báo theo Giờ (24h)',
                'ordering': ['forecast_time'],
                'unique_together': {('location', 'forecast_time')},
            },
        ),
        migrations.DeleteModel(
            name='AIForecast',
        ),
    ]
