# Generated by Django 5.2.8 on 2026-01-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_App', '0004_userprofile_address_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city_name_vn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên tiếng Việt có dấu'),
        ),
    ]
