# Generated by Django 5.2.x on 2026-01-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_App', '0005_location_city_name_vn'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField()),
                ('shortwave_radiation', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weather_App.location')),
            ],
            options={
                'ordering': ['forecast_time'],
                'unique_together': {('location', 'forecast_time')},
            },
        ),
    ]
