# Generated by Django 5.2.8 on 2026-01-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_App', '0005_location_city_name_vn'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainForecastCache',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rain_forecast_cache', serialize=False, to='Weather_App.location')),
                ('data', models.JSONField(verbose_name='Dữ liệu dự báo mưa minutely')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Cache dự báo mưa minutely',
                'verbose_name_plural': '2b. Cache dự báo mưa',
            },
        ),
    ]
