# Generated by Django 6.0 on 2026-01-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_App', '0006_rainforecastcache'),
        ('Weather_App', '0006_solarforecast'),
    ]

    operations = [
    ]
