# Generated by Django 6.0 on 2026-01-22 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_App', '0007_merge_0006_rainforecastcache_0006_solarforecast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Nhiệt độ lúc tìm kiếm')),
                ('weather_code', models.IntegerField(blank=True, null=True, verbose_name='Mã thời tiết')),
                ('is_day', models.BooleanField(default=True, verbose_name='Là ban ngày')),
                ('searched_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian tìm kiếm')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to='Weather_App.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử tìm kiếm',
                'verbose_name_plural': '7. Lịch sử tìm kiếm',
                'ordering': ['-searched_at'],
            },
        ),
    ]
