# Generated by Django 5.2.8 on 2026-01-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_App', '0008_searchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentweathercache',
            options={'verbose_name': 'Cache thời tiết hiện tại', 'verbose_name_plural': '2. Bộ nhớ đệm thời tiết hiện tại'},
        ),
        migrations.AlterModelOptions(
            name='rainforecastcache',
            options={'verbose_name': 'Cache dự báo mưa minutely', 'verbose_name_plural': '3.Bộ nhớ đệm dự báo mưa'},
        ),
        migrations.AlterModelOptions(
            name='solarforecast',
            options={'ordering': ['forecast_time'], 'verbose_name_plural': '8. Dự báo bức xạ mặt trời'},
        ),
        migrations.AlterField(
            model_name='location',
            name='city_name_vn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='HistoricalData',
        ),
    ]
