# Generated by Django 5.2.8 on 2026-01-24 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_App', '0009_alter_currentweathercache_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentweathercache',
            options={'verbose_name': 'bộ nhớ đệm thời tiết hiện tại', 'verbose_name_plural': 'Bộ nhớ đệm thời tiết hiện tại'},
        ),
        migrations.AlterModelOptions(
            name='dailyforecast',
            options={'ordering': ['forecast_date'], 'verbose_name': 'dự báo theo Ngày', 'verbose_name_plural': 'Dự báo theo Ngày (5 ngày)'},
        ),
        migrations.AlterModelOptions(
            name='hourlyforecast',
            options={'ordering': ['forecast_time'], 'verbose_name': 'dự báo theo Giờ (24h)', 'verbose_name_plural': 'Dự báo theo Giờ (24h)'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'vị trí', 'verbose_name_plural': 'Vị trí'},
        ),
        migrations.AlterModelOptions(
            name='rainforecastcache',
            options={'verbose_name': 'bộ nhớ đệm dự báo mưa minutely', 'verbose_name_plural': 'Bộ nhớ đệm dự báo mưa'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-searched_at'], 'verbose_name': 'lịch sử tìm kiếm', 'verbose_name_plural': 'Lịch sử tìm kiếm'},
        ),
        migrations.AlterModelOptions(
            name='solarforecast',
            options={'ordering': ['forecast_time'], 'verbose_name': 'dự báo bức xạ mặt trời', 'verbose_name_plural': 'Dự báo bức xạ mặt trời'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'hồ sơ người dùng', 'verbose_name_plural': 'Hồ sơ người dùng'},
        ),
        migrations.AlterModelOptions(
            name='weatheralert',
            options={'verbose_name': 'cảnh báo thời tiết', 'verbose_name_plural': 'Cảnh báo thời tiết'},
        ),
        migrations.AlterField(
            model_name='currentweathercache',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='current_weather_cache', serialize=False, to='Weather_App.location', verbose_name='Tỉnh thành'),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_forecasts', to='Weather_App.location', verbose_name='Tỉnh thành'),
        ),
        migrations.AlterField(
            model_name='hourlyforecast',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_forecasts', to='Weather_App.location', verbose_name='Tỉnh thành'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city_name',
            field=models.CharField(max_length=100, verbose_name='Tỉnh thành'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city_name_vn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tỉnh thành có dấu'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(max_length=5, verbose_name='Mã quốc gia'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Múi giờ'),
        ),
        migrations.AlterField(
            model_name='rainforecastcache',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rain_forecast_cache', serialize=False, to='Weather_App.location', verbose_name='Tỉnh thành'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='is_day',
            field=models.BooleanField(default=True, verbose_name='Ban ngày'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to='Weather_App.location', verbose_name='Tỉnh thành'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='solarforecast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc'),
        ),
        migrations.AlterField(
            model_name='solarforecast',
            name='forecast_time',
            field=models.DateTimeField(verbose_name='Giờ dự báo'),
        ),
        migrations.AlterField(
            model_name='solarforecast',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weather_App.location', verbose_name='Tỉnh thành'),
        ),
        migrations.AlterField(
            model_name='solarforecast',
            name='shortwave_radiation',
            field=models.FloatField(null=True, verbose_name='Bức xạ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Tỉnh thành'),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='description',
            field=models.TextField(verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='end_time',
            field=models.DateTimeField(verbose_name='Kết thúc'),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='event_name',
            field=models.CharField(max_length=200, verbose_name='Tên sự kiện'),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='Weather_App.location', verbose_name='Tỉnh thành'),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='start_time',
            field=models.DateTimeField(verbose_name='Bắt đầu'),
        ),
    ]
