# Generated by Django 5.2.8 on 2026-01-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_App', '0010_alter_currentweathercache_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyforecast',
            options={'ordering': ['forecast_date'], 'verbose_name': 'dự báo nhiệt độ theo ngày', 'verbose_name_plural': 'Dự báo nhiệt độ theo ngày (5 ngày)'},
        ),
        migrations.AlterModelOptions(
            name='hourlyforecast',
            options={'ordering': ['forecast_time'], 'verbose_name': 'dự báo theo nhiệt độ theo giờ (24h)', 'verbose_name_plural': 'Dự báo theo nhiệt độ theo giờ (24h)'},
        ),
        migrations.AlterModelOptions(
            name='rainforecastcache',
            options={'verbose_name': 'bộ nhớ đệm dự báo mưa', 'verbose_name_plural': 'Bộ nhớ đệm dự báo mưa'},
        ),
    ]
